import os


#################### Particle field line settings ####################
#
# settings pertaining to field lines that are seeded by particle points
#   | magnetic field lines follow the flow of matter, so for particle fields
#   | the seed points are particles of matter
# 
#
# IMPORTANT: all settings related to integration settings (e.g. streamXML stuff)
#            are found in params_run.py


# useParticleTracer:    [bool]  (usually is false, particleTracer is not supported yet)
#                       If false: particlePicker is used to get seed points
#                       If true: particleTracer is used to get seed points                          
#
#                       There are two methods used to get seed points: particlePicker and particleTracer
#                         - particlePicker uses the file called 'paritcles.mon', which tracks the location of 
#                           a large number of particles at every time; particlePicker finds the particles at
#                           the firstTime closest to the specified points, and follows them in time
#                         - particleTracer uses the exact points specified and uses an RK4 integrator along 
#                           with the {vx, vy, vz} velocity h5data to trace its own particles
useParticleTracer = False

# firstTime:    [string] 
#               Similar to offset (an artifact of the old code that is only used in particlePicker)
#				| This is a string that is 017.11f number (5 digits left of the decimal, and 
#				| 11 digits right right of it, both zero padded). The value is the time in code
#				| units of the very first frame. You can find this by looking at the first 
#				| iteration number in the first 3d_data* folder, and convert that into code 
#				| units of time. Then look at at "bhns.xon" and look for that time. Copy 
#				| that time exactly into "firstTime" but not using scientific notation.
#				| If your first time is zero and you use particle seed, check "particle.mon" 
#				| and look at the first line. If the time here is not zero, use this time instead.
firstTime = "00000.00000000000"

# particleFlags:    [bool list]
#                   Specify how many particle field plots you want (up to three, should be easy to add more)
particleFlags = [True, False, False]

# useCustomParticleSeeds:   [bool]
#                           If true: uses seeds from the files in customSeedTXTs
#                           If false: uses seeds generated by the built in seed maker
useCustomParticleSeeds = False

# customSeedTXTs:   [str list]
#                   .txt files with three columns with each row corresponding to a seed
#                   create these by what every means you would like
customSeedTXTs = ["seeds_0.txt", "seeds_1.txt", "seeds_2.txt"]

################ Built in seed maker ################
#               | the built in seed maker creates seeds in rings 
#
# particleCenters:          [float-tuple list] centers of the rings 
#                       e.g. the center of mass of a neutron star
particleCenters = [(0., 0., 0.), (0., 0., 0.), (0., 0., 0.)]

# particleNormVecs:        [float-tuple list] vectors normal to the plane that the seed ring lies on 
#                       e.g. (0., 0., 1.) if you want seeds on xy-plane
particleNormVecs = [(0., 0., 1.), (0., 0., 1.), (0., 0., 1.)]

# particlePairs:            [float-tuple list] list of (radius, height) pairs
#                       radius: is radius of ring
#                       height: if height is not zero, then two rings are placed
#                            above and below the plane defined by the norm vecs
#                               if height is zero, then only one ring is placed
particlePairs = [(1., 0.), (1., 0.), (1., 0.)]

# particleNumSeeds:        [int list] number of points in each ring
particleNumSeeds = [8, 8, 8]

# particleOffsets:          [float list] an angle offset; good to use fractions of pi (e.g. pi/8, pi/10, ...)
from math import pi
particleOffsets = [0., 0., 0.]


########################################################################


#################### Grid point field line settings ####################
#
# settings pertaining to field lines that are seeded by grid points
#   | grid point field lines are used to plot field lines around the poles of black holes
#   | instead of following particles, we want to see how the field arond the black holes behave

# bh_flags are calculated automatically in params.py, values for nonexistant bhs don't matter

# bh_rs:            [float list] rough radius of each black hole, calculate using "bin/misc_scripts/bh_r_calc.py"
bh_rs = [0.1, 0.1, 0.1]

###### Grid seed maker ######
#               | similar to the built-in seed maker for particle seeds
#               | norm vecs and centers are calculated automatically
# gridPairs:        [float-tuple list] (radius, height) pairs, but the values are ratios of the black hole radius
#                       e.g. (0.5 1.5) makes rings with radius=0.5*bh_r at 1.5*bh_r above and below the bh center
gridPairs = [(0.5, 1.5), (0.5, 1.5), (0.5, 1.5)]

# gridNumSteps:     [int list] number of points in each ring
gridNumSteps = [10, 10, 10] 

# gridOffsets:       [float list] an angle offset; good to use fractions of pi (e.g. pi/8, pi/10, ...)
gridOffsets = [0., 0., 0.] 



########################################################################
generalParticleSettings = [useParticleTracer, firstTime, particleFlags, useCustomParticleSeeds, customSeedTXTs]
particleMakerSettings = [particleCenters, particleNormVecs, particlePairs, particleNumSeeds, particleOffsets]
gridMakerSettings = [bh_rs, gridPairs, gridNumSteps, gridOffsets]

params_field = [generalParticleSettings, particleMakerSettings, gridMakerSettings]




